version: '3.1'

services:

  db:
    image: mariadb
    container_name: rabatzspatz_db    
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: rabatzspatz
      MYSQL_USER: rabatzspatz
      MYSQL_PASSWORD: spatznrabatz
    volumes:
      - './data/mysql-init:/docker-entrypoint-initdb.d'

  adminer:
    image: adminer
    container_name: rabatzspatz_admin
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080
      
  app:
    build: app/.
    container_name: rabatzspatz
    restart: unless-stopped
    links:
      - 'db'
    volumes:
      - './data/app:/usr/src/app'
